
export const APP_CONFIG = {
    APPWRITE: {
        KEY: process.env.NEXT_APPWRITE_KEY!,
        ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
        PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
        DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!,
        SHOP_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_SHOP_ID!,
    },
};